### PR TITLE
fix to be "convert_from" as the input

### PR DESCRIPTION
**Pull request by Kingslin0810**

### CODE REVIEW

**Review by jo4356 — CHANGES_REQUESTED** [review]
I think `converter` is even less clear than `convert_to`. Maybe change it to `convert_from`, so we don't have to rewrite the tests/examples

**Comment by Kingslin0810** [comment]
actually from my second thought I feel "converter" makes more sense as whatever I input here is what I convert from. `convert_from` is actually confusing me of what I should input.

**Comment by jo4356** [comment]
The reason why I suggested `convert_from` is because the function was written incorrectly. 

What it does currently is, using the example from the docstring:
`moles_grams_converter("H2O", 0.05555, "moles")` >>> output to 1

It converts 0.05555 "moles" of H2O into 1 grams of H2O. Here the "moles" is the unit the function is converting **from**. 

`converter` does not give an indication of the direction of conversion, which is not intuitive.

**Comment by Kingslin0810** [comment]
good point; I will change it to `convert_from`; thanks.

**Pull request merged**
